from app.routers.auth import router as router_auth
from app.routers.tag import router as router_tag
from app.routers.user import router as router_user
from app.routers.board import router as router_board
from app.routers.list import router as router_list
from app.routers.card import router as router_card
from app.routers.card_comment import router as router_cardcomment
from app.routers.card_tag import router as router_cardtag
from app.routers.card_member import router as router_cardmember
